function [ X ] = ht_to_tensor_8( Xht )

B1 = tensor_contraction(tensor_contraction(Xht{9}, Xht{1}',1,1),...
    Xht{2}', 1, 1);
B2 = tensor_contraction(tensor_contraction(Xht{10}, Xht{3}',1,1),...
     Xht{4}', 1, 1);
B3 = tensor_contraction(tensor_contraction(Xht{11}, Xht{5}',1,1),...
    Xht{6}', 1, 1);
B4 = tensor_contraction(tensor_contraction(Xht{12}, Xht{7}',1,1),...
     Xht{8}', 1, 1);
 
B5 = tensor_contraction(tensor_contraction(Xht{13}, B1,1,1),...
    B2, 1, 1);
B6 = tensor_contraction(tensor_contraction(Xht{14}, B3,1,1),...
     B4, 1, 1);
 
X = tensor_contraction(tensor_contraction(Xht{15}, B5, 1, 1),...
    B6, 1, 1);

end

